### ISSUE TITLE
Compilation issues on a variety of O/S 

### ISSUE THREAD

**Issue by calvert-tagadab** [FreeRDP/FreeRDP-WebConnect#93]
Hi, 

Not sure how active we are here, but - after fixing the issues with Casablanca i see lots of this this on any O/S (including Ubuntu 12):

/root/FreeRDP-WebConnect/wsgate/RDP.cpp: In member function âBOOL wsgate::RDP::PostConnect(freerdp*)â:
/root/FreeRDP-WebConnect/wsgate/RDP.cpp:772:15: error: invalid conversion from âvoid (*)(rdpContext*, rdpPointer*) {aka void (*)(rdp_context*, rdp_pointer*)}â to âpPointer_New {aka int (*)(rdp_context*, rdp_pointer*)}â [-fpermissive]
         p.New = cbPointer_New;
               ^
/root/FreeRDP-WebConnect/wsgate/RDP.cpp:774:15: error: invalid conversion from âvoid (*)(rdpContext*, rdpPointer*) {aka void (*)(rdp_context*, rdp_pointer*)}â to âpPointer_Set {aka int (*)(rdp_context*, rdp_pointer*)}â [-fpermissive]
         p.Set = cbPointer_Set;
               ^
/root/FreeRDP-WebConnect/wsgate/RDP.cpp:775:19: error: invalid conversion from âvoid (*)(rdpContext*) {aka void (*)(rdp_context*)}â to âpPointer_SetNull {aka int (*)(rdp_context*)}â [-fpermissive]
         p.SetNull = cbPointer_SetNull;

... i don't suppose someone could point me in the direction of fixing it? 

Many thanks.

**Comment by alexpilotti** [comment]
With any OS you mean also Windows?

Hi, we currently do continuous builds on Windows but not on Linux, which is on the todo list.

Going to reproduce your issue, we'll get back with some more info.

**Comment by calvert-tagadab** [comment]
Hi, forgive me - i mean any Linux O/S. I've tried Ubuntu 12, 14 and a bunch of different Centos. Thanks for your quick reply!

**Comment by alexpilotti** [comment]
Thanks for the update, we're going to run a build on Ubuntu 14.04 LTS and CentOS 7 to begin with.

**Comment by calvert-tagadab** [comment]
I dont suppose you managed to see if you had the same issue? I'm just curious because if the problem is with me i will continue to try and work out what it is :) Thanks!

**Comment by c64cosmin** [comment]
Use my fork : https://github.com/c64cosmin/FreeRDP-WebConnect.git

sudo install_prereqs.sh
setup-all.sh (might need sudo and -f arg)

It was tested on Ubuntu 14.04 LTS.
We will test it on CentOS 7 soon enough, and then it will be merged on master.

**Comment by rushikeshjadhav** [comment]
** For CentOS7 **

The install_prereqs.sh files has no verification for CentOS7 & fails on CentOS7 stating 
"CentOS 5 not yet supported! Please install prereqs by hand:"
. I'm testing a build by modifying install_prereqs.sh to let it continue on CentOS7.

Will let you know if it succeeds.

**Comment by alexpilotti** [comment]
@rushikeshjadhav are you testing using the @c64cosmin pull request?
We are adding CentOS 7 support there, the PR is currently under test and review

**Comment by rushikeshjadhav** [comment]
@alexpilotti I did try @c64cosmin script and it recognized CentOS7.

On my actual CentOS6 dev machine, I used his script and it ended not able to Compile FreeRDP with following error

...
CMake Warning at client/X11/CMakeLists.txt:115 (message):
  WITH_MANPAGES was set, but xsltproc was not found.  man-pages will not be
  installed
-- Configuring done
CMake Warning (dev) in client/common/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "freerdp-client" has an INTERFACE_LINK_LIBRARIES property which
  differs from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

    tsmf-client;audin-client;rdpei-client;echo-client;rail-client;cliprdr-client;rdpdr-client;drdynvc-client;rdpsnd-client;serial-client;parallel-client;drive-client;tsmf-client-alsa-audio;audin-client-alsa;rdpsnd-client-alsa;freerdp-utils;winpr-crt;winpr-path;winpr-file;winpr-synch;winpr-library;winpr-interlocked;freerdp-core;winpr-crt;winpr-utils

  LINK_INTERFACE_LIBRARIES:

    

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /root/prereqs/FreeRDP
---- Building freerdp ----
make: *** No targets specified and no makefile found.  Stop.
Unable to build FreeRDP package. Exiting...

**Comment by rushikeshjadhav** [comment]
@c64cosmin  Had to modify  setup-all.sh to switch to correct FreeRDP folder. All things are building.
pcsc-lite-devel package was missing from installation script, also its headers need to be corrected from <> to "". I will rerun on a clean machine and would submit patches if required. 
https://gist.github.com/rushikeshjadhav/c798005557a5fec8c58e

**Comment by c64cosmin** [comment]
@rushikeshjadhav I'm doing a test on CentOS6 and I will return shortly.

**Comment by rushikeshjadhav** [comment]
To update further it is observed that devtools-2 does not present on CentOS7.
They should not be needed as the CentOS7 GCC is 4.8.3 already.. I'm not sure if it needs anything else.

FreeRDP-WebConnect package successfully compiles on CentOS7 with @c64cosmin for and https://gist.github.com/rushikeshjadhav/c798005557a5fec8c58e patch.

We may want to remove "# Install CERN's devtoolset-2" section as the repo of slc6 and CentOS7 are incompatible.

In wsgate.ini if we keep
#nonla=true 
then there is a segfault at
wsgate[27357]: segfault at 0 ip 0000000000494c0c sp 00007f51e779cb30 error 6 in wsgate[400000+10e000]

In wsgate.ini if we keep
nonla=true 
then there is a segfault at
wsgate[30296]: segfault at 168 ip 00007f1913356bca sp 00007f190d701be8 error 4 in libfreerdp.so.1.2.4[7f19132c4000+147000]

I think I should start a CentOS7 related separate issue. For this issue Compilation is working so far.
